/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Ejercicio1.Aula;
import Ejercicio1.ListaAula;

/**
 *
 * @author Julio Cesar
 */
public class AsignarAlumno extends javax.swing.JDialog {

    /**
     * Creates new form AsignarAlumno
     */
    public AsignarAlumno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarComboBox();
        this.setLocationRelativeTo(parent);
    }

    public void cargarComboBox() {
        ArrayList<Aula> listadoAulas = ListaAula.getAulas();
        int M = listadoAulas.size();
        String item = null;
        for (int i = 0; i < M; i++) {
            item = listadoAulas.get(i).getNombreAula();
            jComboBox1.addItem(item);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asignar Alumnos");

        jLabel1.setText("Aulas:");

        jLabel2.setText("Cantidad de Alumnos:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Asignar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nombreAula = jComboBox1.getSelectedItem().toString();
        int cantidadAlumnos = Integer.parseInt(jTextField1.getText());
        jComboBox1.setSelectedIndex(0);
        jTextField1.setText(null);
        jTextField1.requestFocus();

        ArrayList<Aula> listadoAulas = ListaAula.getAulas();
        int M = listadoAulas.size();

        int rta = JOptionPane.showConfirmDialog(this, "¿Desea confirmar la operación?",
                "Confirmar asignación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (rta == 0) {
            Aula objAula = null;
            for (int i = 0; i < M; i++) {
                objAula = listadoAulas.get(i);
                if (objAula.getNombreAula().equalsIgnoreCase(nombreAula)) {
                    if (objAula.getCantidadBancos() >= cantidadAlumnos) {
                        objAula.setCantidadAlumnos(cantidadAlumnos);
                        listadoAulas.set(i, objAula);
                        JOptionPane.showMessageDialog(this, "La asignación se realizó correctamente.");
                    } else {
                        JOptionPane.showMessageDialog(this, cantidadAlumnos
                                + " alumnos no pueden asignarse a un aula con "
                                + objAula.getCantidadBancos()
                                + " bancos.", "Título del Modal", JOptionPane.WARNING_MESSAGE);
                    }
                }

            }

        }

        DefaultTableModel dataTable = new DefaultTableModel();
        dataTable.addColumn("Nombre Aula");
        dataTable.addColumn("Cantidad de Bancos");
        dataTable.addColumn("Cantidad de Alumnos");

        Object[] fila = new Object[3];
        for (int i = 0; i < M; i++) {
            fila[0] = listadoAulas.get(i).getNombreAula();
            fila[1] = listadoAulas.get(i).getCantidadBancos();
            fila[2] = listadoAulas.get(i).getCantidadAlumnos();
            dataTable.addRow(fila);
        }

        jTable1.setModel(dataTable);

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
